test

diff --git a/.github/workflows/prowler.yml b/.github/workflows/prowler.yml
--- a/.github/workflows/prowler.yml
+++ b/.github/workflows/prowler.yml
@@ -24,18 +24,11 @@ jobs:
           pip install prowler
           pip install "pyOpenSSL>=22.0.0" "urllib3>=1.26.0"
 
-      - name: Configure AWS Credentials
+      - name: Set AWS Environment Variables
         run: |
-          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
-          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
-          aws configure set aws_session_token "${{ secrets.AWS_SESSION_TOKEN }}"
-          
-
-      - name: Print Environment Variables
-        run: |
-          echo "AWS Access Key: ${{ secrets.AWS_ACCESS_KEY_ID }}"
-          echo "AWS Secret Key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
-          aws configure list
+          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
+          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
+          echo "AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}" >> $GITHUB_ENV
 
       - name: Run Prowler Scan
         id: prowler_scan
@@ -47,24 +40,27 @@ jobs:
           error_file="error_all_checks.log"
 
           echo "Running all checks..."
-          if timeout 300 prowler aws -c all --output-formats json-ocsf --output-filename "$report_file_json" --verbose > "$error_file"; then
-            # Run CSV output as well
-            prowler aws -c all --output-formats csv --output-filename "$report_file_csv" || true
-            
-            # Check if report files were created
-            if [[ -f "$report_file_json" && -f "$report_file_csv" ]]; then
-              echo "All checks completed successfully."
-              echo "scan_status=success" >> $GITHUB_ENV
-            else
-              echo "One or both report files were not created."
-              echo "scan_status=failed" >> $GITHUB_ENV
-              exit 1
-            fi
+          if timeout 300 AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
+             AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
+             AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }} \
+             prowler aws -c all --output-formats json-ocsf --output-filename "$report_file_json" --verbose > "$error_file"; then
+             # Run CSV output as well
+             prowler aws -c all --output-formats csv --output-filename "$report_file_csv" || true
+
+             # Check if report files were created
+             if [[ -f "$report_file_json" && -f "$report_file_csv" ]]; then
+               echo "All checks completed successfully."
+               echo "scan_status=success" >> $GITHUB_ENV
+             else
+               echo "One or both report files were not created."
+               echo "scan_status=failed" >> $GITHUB_ENV
+               exit 1
+             fi
           else
-            echo "Checks failed. See error log for details:"
-            cat "$error_file"
-            echo "scan_status=failed" >> $GITHUB_ENV
-            exit 1
+             echo "Checks failed. See error log for details:"
+             cat "$error_file"
+             echo "scan_status=failed" >> $GITHUB_ENV
+             exit 1
           fi
 
       - name: Send Reports to Slack
