test

diff --git a/.github/workflows/prowler.yml b/.github/workflows/prowler.yml
--- a/.github/workflows/prowler.yml
+++ b/.github/workflows/prowler.yml
@@ -30,31 +30,54 @@ jobs:
           aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
           aws configure set aws_session_token "${{ secrets.AWS_SESSION_TOKEN }}"
 
-      - name: Run Prowler Scan
-        id: prowler_scan
+      - name: Run Prowler JSON Scan
+        id: prowler_json_scan
         run: |
           set -e
           report_prefix="prowler-output-$(date +%Y%m%d%H%M%S)"
-          error_file="error_all_checks.log"
+          report_file_json="${report_prefix}.ocsf.json"
+          error_file="error_json.log"
 
-          echo "Running all checks..."
+          echo "Running Prowler JSON checks..."
 
-          # Run the Prowler scan
-          if timeout 1200 prowler aws -c all --output-formats json-ocsf,csv --output-filename "$report_prefix" --verbose > "$error_file" 2>&1; then
-            # Check if report files were created
-            report_file_json="${report_prefix}.ocsf.json"
-            report_file_csv="${report_prefix}.csv"
-
-            if [[ -f "$report_file_json" && -f "$report_file_csv" ]]; then
-              echo "All checks completed successfully."
+          # Run the Prowler scan for JSON output
+          if timeout 600 prowler aws -c all --output-formats json-ocsf --output-filename "$report_prefix" --verbose > "$error_file" 2>&1; then
+            if [[ -f "$report_file_json" ]]; then
+              echo "JSON report created successfully."
               echo "scan_status=success" >> $GITHUB_ENV
             else
-              echo "One or both report files were not created." | tee -a "$error_file"
+              echo "JSON report file was not created." | tee -a "$error_file"
               echo "scan_status=failed" >> $GITHUB_ENV
               exit 1
             fi
           else
-            echo "Checks failed. See error log for details:" | tee -a "$error_file"
+            echo "JSON checks failed. See error log for details:" | tee -a "$error_file"
+            cat "$error_file"
+            echo "scan_status=failed" >> $GITHUB_ENV
+            exit 1
+          fi
+
+      - name: Run Prowler CSV Scan
+        id: prowler_csv_scan
+        run: |
+          set -e
+          report_prefix="prowler-output-$(date +%Y%m%d%H%M%S)"
+          report_file_csv="${report_prefix}.csv"
+          error_file="error_csv.log"
+
+          echo "Running Prowler CSV checks..."
+
+          # Run the Prowler scan for CSV output
+          if timeout 600 prowler aws -c all --output-formats csv --output-filename "$report_prefix" --verbose > "$error_file" 2>&1; then
+            if [[ -f "$report_file_csv" ]]; then
+              echo "CSV report created successfully."
+            else
+              echo "CSV report file was not created." | tee -a "$error_file"
+              echo "scan_status=failed" >> $GITHUB_ENV
+              exit 1
+            fi
+          else
+            echo "CSV checks failed. See error log for details:" | tee -a "$error_file"
             cat "$error_file"
             echo "scan_status=failed" >> $GITHUB_ENV
             exit 1
@@ -64,10 +87,11 @@ jobs:
         if: failure()
         run: |
           echo "Error Log Contents:"
-          if [[ -f error_all_checks.log ]]; then
-            cat error_all_checks.log
-          else
-            echo "No error log found."
+          if [[ -f error_json.log ]]; then
+            cat error_json.log
+          fi
+          if [[ -f error_csv.log ]]; then
+            cat error_csv.log
           fi
 
       - name: Send Reports to Slack
@@ -90,17 +114,17 @@ jobs:
           }
 
           # Check and send JSON report file
-          report_file_json="${report_prefix}.ocsf.json"
-          if [[ -f "${report_file_json}" ]]; then
-            send_file_to_slack "${report_file_json}" "Prowler Scan JSON Report"
+          report_file_json="prowler-output-*.ocsf.json"
+          if ls $report_file_json 1> /dev/null 2>&1; then
+            send_file_to_slack "$report_file_json" "Prowler Scan JSON Report"
           else
             echo "JSON report file not found. Skipping."
           fi
 
           # Check and send CSV report file
-          report_file_csv="${report_prefix}.csv"
-          if [[ -f "${report_file_csv}" ]]; then
-            send_file_to_slack "${report_file_csv}" "Prowler Scan CSV Report"
+          report_file_csv="prowler-output-*.csv"
+          if ls $report_file_csv 1> /dev/null 2>&1; then
+            send_file_to_slack "$report_file_csv" "Prowler Scan CSV Report"
           else
             echo "CSV report file not found. Skipping."
           fi
