test

diff --git a/.github/workflows/prowler.yml b/.github/workflows/prowler.yml
--- a/.github/workflows/prowler.yml
+++ b/.github/workflows/prowler.yml
@@ -28,7 +28,7 @@ jobs:
           aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
           aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
           aws configure set aws_session_token "${{ secrets.AWS_SESSION_TOKEN }}"
-        
+          aws configure set region us-east-1  # Add this line to specify your region
 
       - name: Run Prowler Scan
         id: prowler_scan
@@ -48,9 +48,17 @@ jobs:
           fi
 
       - name: Send Reports to Slack
+        if: env.scan_status == 'success'  # Only send if the scan was successful
         run: |
           content=$(<report_check135.txt)
           echo "Sending report to Slack..."
-          curl -X POST -H 'Content-type: application/json' --data "{
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H 'Content-type: application/json' --data "{
             \"text\": \"*Prowler Scan Report for check135*\\n\`\`\`${content}\`\`\`"
-          }" "${{ secrets.SLACK_WEBHOOK_URL }}"
+          }" "${{ secrets.SLACK_WEBHOOK_URL }}")
+
+          if [ "$response" -ne 200 ]; then
+            echo "Failed to send report to Slack. HTTP status code: $response"
+            exit 1
+          else
+            echo "Report sent to Slack successfully."
+          fi
